src/Entity/Article.php
<?php

    namespace App\Entity;

    use App\Repository\CommentRepository;
    use Doctrine\Common\Collections\ArrayCollection;
    use Doctrine\Common\Collections\Collection;
    use Doctrine\ORM\Mapping as ORM;
    use Gedmo\Mapping\Annotation as Gedmo;
    use Gedmo\Timestampable\Traits\TimestampableEntity;

    /**
     * @ORM\Entity(repositoryClass="App\Repository\ArticleRepository")
     */
    class Article
    {
        use TimestampableEntity;

        /**
         * @ORM\Id()
         * @ORM\GeneratedValue()
         * @ORM\Column(type="integer")
         */
        private $id;

        /**
         * @ORM\Column(type="string", length=255)
         */
        private $title;

        /**
         * @ORM\Column(type="string", length=100, unique=true)
         * @Gedmo\Slug(fields={"title"})
         */
        private $slug;

        /**
         * @ORM\Column(type="text", nullable=true)
         */
        private $content;

        /**
         * @ORM\Column(type="datetime", nullable=true)
         */
        private $publishedAt;

        /**
         * @ORM\Column(type="integer")
         */
        private $heartCount = 0;

        /**
         * @ORM\OneToMany(targetEntity="App\Entity\Comment", mappedBy="article", fetch="EXTRA_LAZY")
         * @ORM\OrderBy({"createdAt" = "DESC"})
         *
         */
        private $comments;

        /**
         * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="articles", fetch="EAGER")
         * @ORM\JoinColumn(nullable=true, onDelete="SET NULL")
         */
        private $author;

        /**
         * @ORM\ManyToMany(targetEntity="App\Entity\Tag", mappedBy="article")
         */
        private $tags;

        public function __construct()
        {
            $this->comments = new ArrayCollection();
            $this->tags = new ArrayCollection();
        }

        public function getId(): ?int
        {
            return $this->id;
        }

        public function getTitle(): ?string
        {
            return $this->title;
        }

        public function setTitle(string $title): self
        {
            $this->title = $title;

            return $this;
        }

        public function getSlug(): ?string
        {
            return $this->slug;
        }

        public function setSlug(string $slug): self
        {
            $this->slug = $slug;

            return $this;
        }

        public function getContent(): ?string
        {
            return $this->content;
        }

        public function setContent(?string $content): self
        {
            $this->content = $content;

            return $this;
        }

        public function getPublishedAt(): ?\DateTimeInterface
        {
            return $this->publishedAt;
        }

        public function setPublishedAt(?\DateTimeInterface $publishedAt): self
        {
            $this->publishedAt = $publishedAt;

            return $this;
        }

        public function getHeartCount(): ?int
        {
            return $this->heartCount;
        }

        public function incrementHeartCount(): self
        {
            $this->heartCount = $this->heartCount + 1;

            return $this;
        }

        public function decrementHeartCount(): self
        {
            $this->heartCount = $this->heartCount - 1;

            return $this;
        }

        public function setHeartCount($heartCount): self
        {
            $this->heartCount = $heartCount;

            return $this;
        }

        /**
         * @return Collection|Comment[]
         */
        public function getComments(): Collection
        {
            return $this->comments;
        }

        public function addComment(Comment $comment): self
        {
            if (!$this->comments->contains($comment)) {
                $this->comments[] = $comment;
                $comment->setArticle($this);
            }

            return $this;
        }

        public function removeComment(Comment $comment): self
        {
            if ($this->comments->contains($comment)) {
                $this->comments->removeElement($comment);
                // set the owning side to null (unless already changed)
                if ($comment->getArticle() === $this) {
                    $comment->setArticle(null);
                }
            }

            return $this;
        }

        public function getAuthor(): ?User
        {
            return $this->author;
        }

        public function setAuthor(?User $author): self
        {
            $this->author = $author;

            return $this;
        }

        /**
         * @return Collection|Tag[]
         */
        public function getTags(): Collection
        {
            return $this->tags;
        }

        public function addTag(Tag $tag): self
        {
            if (!$this->tags->contains($tag)) {
                $this->tags[] = $tag;
                $tag->addArticle($this);
            }

            return $this;
        }

        public function removeTag(Tag $tag): self
        {
            if ($this->tags->contains($tag)) {
                $this->tags->removeElement($tag);
                $tag->removeArticle($this);
            }

            return $this;
        }

        /**
         * @return Collection|Comment[]
         */
        public function getNonDeletedComments(): Collection
        {
            $criteria = CommentRepository::createNonDeletedCriteria();

            return $this->comments->matching($criteria);
        }

        public function getPublishedAtString(): string
        {
            if ($this->getPublishedAt())
                return $this->getPublishedAt()->format("Y-m-d H:i:s");
            else
                return "null";
        }

        public function getCreatedAtString(): string
        {
            return $this->getCreatedAt()->format("Y-m-d H:i:s");
        }

        /**
         * @return bool
         */
        public function isPublished(): bool
        {
            if ($this->getPublishedAt())
                return true;
            else
                return false;
        }

        public function unpublish()
        {
            $this->publishedAt = null;
        }

        public function setTags($tags)
        {
            if ($tags) {
                $this->clearTags();
                /** @var Tag $tag */
                foreach ($tags as $tag) {
                    $this->tags[] = $tag;
                    $tag->addArticle($this);
                }
            }
        }

        public function clearTags()
        {
            /** @var Tag $tag */
            foreach ($this->tags as $tag) {
                $tag->removeArticle($this);
            }
            unset($this->tags);
            $this->tags = new ArrayCollection();
        }


    }

src/Controller/ArticleController.php
<?php

    namespace App\Controller;

    use App\Entity\Article;
    use App\Entity\Comment;
    use App\Form\CommentFormType;
    use App\Repository\ArticleRepository;
    use App\Repository\CommentRepository;
    use App\Repository\CuriosityRepository;
    use Knp\Component\Pager\PaginatorInterface;
    use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
    use Symfony\Component\HttpFoundation\Request;
    use Symfony\Component\Routing\Annotation\Route;

    class ArticleController extends AbstractController
    {
        /**
         * @Route("/", name="app_homepage")
         * @param ArticleRepository $articleRepository
         * @param CuriosityRepository $curiosityRepository
         * @param Request $request
         * @param PaginatorInterface $paginator
         * @return \Symfony\Component\HttpFoundation\Response
         * @throws \Exception
         */
        public function homepage(ArticleRepository $articleRepository, CuriosityRepository $curiosityRepository, Request $request, PaginatorInterface $paginator)
        {
            $query = $articleRepository->findAllPublishedOrderedByNewest();
            $curiosities = $curiosityRepository->getLimitedOrderedByCreatedAtDESC(3);


            $articles = $paginator->paginate(
                $query, /* query NOT result */
                $request->query->getInt('page', 1)/*page number*/,
                5/*limit per page*/

            );
            $articles->setCustomParameters(array(
                'size' => 'small',
                'rounded' => false,
                'span_class' => 'block-warning'
            ));

            return $this->render('article/index.html.twig', [
                'articles' => $articles,
                'curiosities' => $curiosities,
            ]);
        }

        /**
         * @Route("/about", name="app_about")
         */
        public function about()
        {
            return $this->render('article/about.html.twig');
        }

        /**
         * @Route("/articles/{slug}", name="app_articles")
         * @param Request $request
         * @param Article $article
         * @param CommentRepository $commentRepository
         * @param $slug
         * @param SecurityController $securityController
         * @return \Symfony\Component\HttpFoundation\Response
         */
        public function articles(Request $request, Article $article, CommentRepository $commentRepository, $slug, SecurityController $securityController)
        {
            /** @var Comment[] $comments */
            $comments = $commentRepository->getCommentsFromArticleId($article->getId());
            $comment = new Comment();
            $form = $this->createForm(CommentFormType::class, $comment);
            $form->handleRequest($request);
            if ($form->isSubmitted() && $form->isValid()) {
                if (!$this->isGranted("ROLE_USER")) {
                    $this->addFlash('success', 'Najpierw się zaloguj!');
                    return $this->redirectToRoute('app_login');
                }

                $comment->setContent($form->get('content')->getData());
                $comment->setIsDeleted(false);
                $user = $securityController->getUser();
                $comment->setUser($user);
                $comment->setArticle($article);

                $entityManager = $this->getDoctrine()->getManager();
                $entityManager->persist($comment);
                $entityManager->flush();

                unset($form);
                unset($comment);

                $this->addFlash('success', 'Komentarz został wysłany');
                return $this->redirectToRoute('app_articles', ['slug' => $slug]);
            }
            /** @var Article $article */
            /** @var Comment[] $comments */
            return $this->render('article/articles.html.twig', [
                'article' => $article,
                'comments' => $comments,
                'commentForm' => $form->createView(),
            ]);
        }
    }

templates/article/about.html.twig
{% extends 'base.html.twig' %}
{% block title %}Home{% endblock %}

{% block stylesheets %}
    {{ parent() }}
    <link rel="stylesheet" href="{{ asset("css/homepage.css") }}">
{% endblock %}

{% block body %}
    <section class="section section-top section-full">
        <div class="bg-cover" id="bg-img"></div>
        <div class="bg-overlay"></div>
        <div class="container">
            <div class="row justify-content-center align-items-center p-5">
                <div class="col-md-8 col-lg-7">
                    <h1 class="shadowed text-white text-center mb-4 text">
                        Blog dla fanów motoryzacji
                    </h1>
                    <p class="shadowed lead text-white text-center mb-4">
                        Nasz blog powstał z myślą o osobach, u których w żyłach płynie benzyna. Porady ekspertów,
                        ciekawostki, fakty i mity, opinie użytkowników. Jeśli interesujesz się motoryzacją tak jak my to
                        bardzo dobrze trafiłeś!
                    </p>
                    <p class="text-center mb-0">
                        <a href="{{ path("app_homepage") }}" class="btn btn-lg btn-warning">
                            Sprawdź nowe artykuły
                        </a>
                    </p>
                </div>
            </div>
        </div>
    </section>
    <section class="section p-5">
        <div class="container text-md-left">
            <div class="row align-items-center">
                <div class="col-md-6 col-lg-5 offset-lg-1">
                    <img src="{{ asset("img/cars.jpg") }}" alt="cars.jpg" class="img-fluid">
                </div>
                <div class="col-md-6 col-lg-4 offset-lg-1">
                    <h2 class="shadowed-white"> Wszystkie pojazdy! </h2>
                    <p class="text-muted"> Marka? Model? U nas nie jest to ważne. Łączymy wszystkich fanów motoryzacji w
                        jednym miejscu. Interesujemy się każdą marką. Uwielbiamy zarówno klasyki jak i najnowsze
                        modele.</p>
                </div>
            </div>
        </div>
    </section>
    <section class="section p-5">
        <div class="container text-md-right">
            <div class="row align-items-center">
                <div class="col-md-6 col-lg-5 offset-lg-1 order-md-2">
                    <img src="{{ asset("img/desk.jpg") }}" alt="desk.jpg" class="img-fluid">
                </div>
                <div class="col-md-6 col-lg-4 offset-lg-1 order-md-1">
                    <h2 class="shadowed-white"> Każdy temat! </h2>
                    <p class="text-muted text">Nowości ze świata motoryzacji, fakty o których nie wiedziałeś, porady od
                        ekspertów, podsumowania najważniejszych motoryzacyjnych wydarzeń, wywiady z ludźmi z branży.
                    </p>
                    <a href="{{ path("app_register") }}" class="btn btn-dark">Zarejestruj się teraz!</a>
                </div>
            </div>
        </div>
    </section>

{% endblock %}

templates/article/articles.html.twig
{% extends 'base.html.twig' %}

{% block title %}Artykuły{% endblock %}

{% block stylesheets %}
    {{ parent() }}
    <style>
        .p-5 {
            width: 75%;
            margin: auto;
        }

        .conteiner {
            width: 70%;
            display: flex;
            justify-content: center;
            margin: auto;
        }


        .comments {
            float: left;
            padding: 5px;
        }


        .comments > a:link {
            color: black;
        }


        .comments > a:hover {
            text-decoration: none;
        }


        .comments > a:visited {
            color: black;
        }


        #center {
            display: block;
            margin-left: auto;
            margin-right: auto;
            width: 70%;
        }

        .id {
            padding: 15px;
        }

        .title {
            padding: 20px 0;

        }

        .title > h1 {
            font-weight: 700;
            font-size: 50px;
        }

        .authorimg {
            /* float: left; */
            padding: 10px;
        }

        .avatar {
            float: left;
            width: 50px;
            height: 50px;
        }

        .author {
            float: left;
            padding-left: 10px;

        }

        .author > p {
            font-size: 35px;
            font-weight: 400;
        }

        .date {
            clear: both;
            padding-bottom: 10px;
        }

        .photo {
            clear: both;
        }


        .tags {
            clear: both;
            padding: 5px;
        }

        .desc {
            padding: 20px 0;
            text-align: justify;
        }

        .comm {
            clear: both;
            padding: 10px;
        }

        .borderr {
            border: none;
        }

        .comment {
            /* border-bottom: 3px solid #ddd; */
            padding: 15px;
        }

        .border :last-child {
            border-bottom: none;
        }

        .av {
            width: 70%;
            padding: 10px;
            margin: auto;
        }

        .av > img {
            width: 75px;
            height: auto;
        }

        .form-control {
            padding: 5px;
        }

        .main {
            padding: 15px 0;
        }
    </style>
{% endblock %}

{% block body %}
    <section class="p-5">
        <div class="conteiner">

            <div class="article">
                <div class="title">
                    <h1>{{ article.title }}</h1>
                </div>
                <div class="authorimg">
                    <img class="avatar" src="{{ asset(article.author.photo.path) }}" alt="avatar">

                    <div class="author">
                        <p>{{ article.author.firstName }} {{ article.author.lastName }}</p>
                    </div>
                    <div class="date">
                        <span>Added {{ article.publishedAtString|ago }}</span>
                    </div>
                </div>
                {#<div class="photo">#}
                {#<img src="../img/paliwo.jpg" class="img-thumbnail" id="center" alt="">#}
                {#</div>#}

                <div class="desc">
                    <p class="h5 main">
                        {{ article.content }}
                    </p>
                </div>
                <div class="tags">
                    {% for tag in article.tags %}
                        <a class="badge badge-info" href="{{ path('app_tags', { id:tag.id }) }}">{{ tag.name }}</a>
                    {% endfor %}
                </div>

                <div class="comm">
                    <h2>Komentarze ({{ article.nonDeletedComments|length }}):</h2>
                    <div class="borderr">
                        {% for comment in comments %}
                            <div class="comment">
                                <div class="row">
                                    <div class="col-2">
                                        <div class="av">
                                            <img src="{{ asset(comment.user.photo.path) }}" class="rounded" alt="">
                                        </div>
                                    </div>
                                    <div class="col-10">
                                        <div class="comm_author">
                                            {% if comment.user.id == article.author.id %}
                                                <h4 class="text-info">{{ comment.user.firstName }} {{ comment.user.lastName }}</h4>
                                            {% else %}
                                                {% if comment.user.firstName and comment.user.firstName %}
                                                    <h4>{{ comment.user.firstName }} {{ comment.user.lastName }}</h4>
                                                {% else %}
                                                    <h4>{{ comment.user.email }}</h4>
                                                {% endif %}
                                            {% endif %}
                                        </div>
                                        <div class="datee">
                                            <p>{{ comment.createdAtString|ago }}</p>
                                        </div>
                                        <div class="centering-wrapper">
                                            <div class="content">
                                                <p>{{ comment.content }}</p>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        {% endfor %}

                        {% for message in app.session.flashBag.get('success') %}
                            <div class="alert alert-success">
                                {{ message }}
                            </div>
                        {% endfor %}

                        <div class="new">
                            {{ form_start(commentForm, {label_attr: {class: 'form-signin'}}) }}
                            {{ form_errors(commentForm.content) }}
                            {{ form_row(commentForm.content, {
                                attr: { placeholder: 'Treść wiadomości', style: 'height:100px' },
                                label_attr: { class: 'sr-only' }
                            }) }}
                            <button class="btn btn-lg btn-dark btn-block" type="submit">Prześlij wiadomość</button>

                            {{ form_end(commentForm) }}
                        </div>


                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

templates/article/contact.html.twig
{% extends 'base.html.twig' %}

{% block title %}Kontakt{% endblock %}

{% block stylesheets %}
    {{ parent() }}
    <link rel="stylesheet" href="{{ asset("css/homepage.css") }}">
{% endblock %}

{% block body %}
    {% if is_granted('ROLE_ADMIN') %}
        {% if areNotMessages == false %}
            <div class="alert alert-danger">
                <h3>Masz zalegające wiadomości w <a href="{{ path('app_show_emails_contact') }}"
                                                    class="link">skrzynce</a>! </h3>
            </div>
        {% endif %}
    {% endif %}
    {% for message in app.session.flashBag.peek('success') %}
        <div class="alert alert-success">
            {{ message }}
        </div>
    {% endfor %}
    <div class="container mt-5">
        <h1 class="display-4 text-center">Skontaktuj się z nami!</h1>
        <p class="text-center">Jeśli masz jakiś problem, bądź pytanie.</p>
        {{ form_start(contactForm, {label_attr: {class: 'form-signin'}}) }}
        {{ form_errors(contactForm.email) }}
        {{ form_row(contactForm.email, {
            attr: { placeholder: 'Email' },
            label_attr: { class: 'sr-only' }
        }) }}
        {{ form_errors(contactForm.content) }}
        {{ form_row(contactForm.content, {
            attr: { placeholder: 'Treść wiadomości', style: 'height:180px' },
            label_attr: { class: 'sr-only' }
        }) }}
        <button class="btn btn-lg btn-primary btn-block" type="submit">Prześlij wiadomość</button>

        {{ form_end(contactForm) }}
    </div>
{% endblock %}

templates/article/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Strona główna{% endblock %}

{% block stylesheets %}
    {{ parent() }}
{% endblock %}


{% block body %}
    <div class="container">
        <div class="row">
            <div class="col-8">
                <h1 id="main-header" class="text-center shadowed-white">Ostatnie artykuły</h1>
                {% for article in articles %}
                    <div class="article-container my-1 p-1">
                        <a href="{{ path('app_articles', {slug: article.slug}) }}">
                            <div class="article-title d-inline-block pl-3 align-middle">
                                <span>{{ article.title }}</span>
                                {#<small class="ml-5"><i class="fas fa-heart"#}
                                {#style="color: red;"></i> {{ article.heartCount }}#}
                                {#</small>#}

                                {% if article.tags|length %}
                                    <br>
                                    {% for tag in article.tags %}
                                        <small>
                                            <span class="badge badge-warning">{{ tag.name }}</span>
                                        </small>
                                    {% endfor %}
                                    <br>
                                {% endif %}
                                <div>{{ article.content|truncate(40) }}</div>
                                <span class="align-left article-details">
                                    <img class="article-author-img rounded-circle"
                                         src="{{ asset(article.author.photo.path) }}"
                                         alt="avatar"> {{ article.author }} </span>
                                <small>
                                    <i class="far fa-comment text-center ml-5"></i> {{ article.nondeletedcomments|length }}
                                </small>
                                <span class="pl-5 article-details float-right"> {{ article.publishedAt ? article.publishedAt|ago }}</span>
                            </div>
                        </a>
                    </div>
                {% endfor %}
                {{ knp_pagination_render(articles) }}
            </div>
            <div class="col-4">
                {% if is_granted("ROLE_ADMIN") %}
                    <a style="color:black;" href="{{ path('app_admin_curiosities') }}"><h2 class="text-center">
                            Ciekawoski</h2></a>
                {% else %}
                    <h2 class="text-center">Ciekawoski</h2>
                {% endif %}
                {% for cur in curiosities %}
                    <div class="p-2">
                        <h3 class="text-right font-weight-bold">{{ cur.title }}</h3>
                        <p class="text-muted">{{ cur.text }}</p>
                        <small><a href="{{ cur.link }}">Czytaj dalej...</a></small>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

templates/article/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Artykuły{% endblock %}

{% block body %}{% endblock %}